### ISSUE TITLE
Main page love

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/Wikiba.se-2017#14]
- Improve wording
- Use different icons for the points as done for Wikibase Repo
- Align the icons and text correctly
- Align "Projects Powered by Wikibase" correctly
- Fix the excessive whitespace between "Main projects" and "Why use Wikibase"

I might also have messed up the HTML structure itself, and suspect the wrong css classes are used since this is not a two column layout.

**Comment by ghost** [comment]
Fixed the alignment, structural and whitespace issues in f75a0d7c87717e53b538a6cbcd2b8366883b833b

**Comment by JeroenDeDauw** [comment]
\o/ @jakob-WMDE please close the item when you think you undid my damage to the look of the thing :)

**Comment by ghost** [comment]
Added different icons in ba5fc5ec9962f5f0fc6731f43257c1a98b0a2ed3. Looking better now!

**Comment by JeroenDeDauw** [comment]
\o/ http://wikiba.se/
