### ISSUE TITLE
Non-library listing

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/Wikiba.se-2017#15]
It's clear that libraries go on the "[components page](http://wikiba.se/components/)". For non libraries things are less clear.
- The "Tools and infrastructure" section does not really belong on the components page.
- We do not have a good place to list interoperable software, for instance bot libraries that support Wikibase (if they only support Wikidata, we cannot list them here, so we might not have many).
- We might end up with quite a few applications. Wikibase Repository, Wikibase Client, Wikibase Query, Wikibase Commons, an app for replication, etc. Some of those will be not as significant as other, and one might be interested in only one specific type (ie MediaWiki extension).

Possible steps to take:
- Rename "applications" to "mediawiki extensions" and introduce a new "applications" page when needed
- Add an "associated projects and tools" page, with things such as "Wikidata builder", "WDTK" and "Semantic MediaWiki"

**Comment by JeroenDeDauw** [comment]
@AbrahamWMDE @thiemowmde @jakob-WMDE

**Comment by Ladsgroup** [comment]
Moved to phabricator: https://phabricator.wikimedia.org/T171663
