### ISSUE TITLE
create footer

### ISSUE THREAD

**Issue by Benestar** [wmde/Wikiba.se-2017#17]
I think this website should have a footer with some useful links which do not have to be prominent but should be visible on each side. We can also add the license and the link to an imprint there.

**Comment by JeroenDeDauw** [comment]
So what would these links be? You mentioned license and imprint. Having a full list would be nice.

**Comment by JeroenDeDauw** [comment]
@Benestar ?

**Comment by Ladsgroup** [comment]
Moved to phabricator: https://phabricator.wikimedia.org/T171659
