### ISSUE TITLE
Editability of the site

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/Wikiba.se-2017#19]
Right now people can edit the site via this git repo, though a manual deployment step has to be done by one of two people. Removing this barrier would be good.

[Bug: T99530](https://phabricator.wikimedia.org/T99530)
[Bug: T99531](https://phabricator.wikimedia.org/T99531)

**Comment by JeroenDeDauw** [comment]
Idea: use GitHub pages to host the site. Since it's all static anyway, this ought to work just fine. We'd need a new git repo to which people can push build versions of the site, which is all they'd need to do to deploy.

**Comment by AbrahamWMDE** [comment]
sounds good to me.

**Comment by ghost** [comment]
Pushing it to another GitHub repository sounds like an unnecessary extra step for people who want to edit the site. Wouldn't it be simpler to have a job running somewhere to build and deploy the site every hour or so?

**Comment by JeroenDeDauw** [comment]
> Wouldn't it be simpler to have a job running somewhere to build and deploy the site every hour or so?

It'd be simpler for the contributors yes. It's less simple to set up though, as you need to have a place where this runs, and this place needs access to the server that has the site on it. If we can do this, then fantastic, that'd indeed be much nicer.

**Comment by JeroenDeDauw** [comment]
If we did not just have FTP access to the server that runs the site, we could just have a cron job running on it. That'd be much simpler.

**Comment by JeroenDeDauw** [comment]
@jakob-WMDE You did some stuff in this direction... did you finish anything?

**Comment by addshore** [comment]
Could just have a hook on merge force an update?

**Comment by JeroenDeDauw** [comment]
> Could just have a hook on merge force an update?

Can you explain in more detail?

**Comment by jakobw** [comment]
@JeroenDeDauw I wrote a bash/ruby script that generates the production files and uploads them to an FTP server. It works but it's very hacky and still needs a place to run.

**Comment by addshore** [comment]
Well, I don't know where the site is currently hosted, but just have a github hook push to a URL on every merge into master, this url can run a script on the server the sit is hosted on, check the validity of the hook (ie. it cam from github) and then simply pull the new version of master is everything looks fine!

Steps:
1. Create a location github can post to through a hook
2. Point a github hook to that url
3. Fire some tests hooks to see what data is received and what needs to be checked, then build up a script that will do said checks and pull the new data
4. Have a beer!

**Comment by JeroenDeDauw** [comment]
Alternative steps:
- Get a beer
- Rage addshore into doing original steps for a beer
- Wait till done, then send beer
- Profit

**Comment by JeroenDeDauw** [comment]
That's a great idea though - avoids having anything needing to know how to access the server or needing to have code run somewhere else. Also put the site gen and the site together.

**Comment by Ladsgroup** [comment]
This is part of https://phabricator.wikimedia.org/T99531, so closing this.
