### ISSUE TITLE
Fork me on GitHub

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/Wikiba.se-2017#2]
Should have something that makes clear how people can contrib to the site. Typically this is done with a "Fork me on GitHub" thing: https://github.com/blog/273-github-ribbons

Perhaps we can also have an edit link show for each page?

**Comment by AbrahamWMDE** [comment]
edit link would be great!

**Comment by JeroenDeDauw** [comment]
Done by @jakob-WMDE in 35943a5f76e578a9bfcd89e559876b8af2775599
