### ISSUE TITLE
Add a news section

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/Wikiba.se-2017#20]
Having a section with noteworthy news items, such as for instance the DataModel 1.0 release, would be nice. Setting up a whole blog for this, as a lot of projects are doing, is perhaps more than we need. Having a simple list in which we can have a header, a small summary and a link to an actual blog post or article is probably good enough.

**Comment by Ladsgroup** [comment]
Moved to phabricator: https://phabricator.wikimedia.org/T171661
