### ISSUE TITLE
Redirect old page on MediaWiki.org

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/Wikiba.se-2017#21]
https://www.mediawiki.org/wiki/Wikibase

Before we redirect this to the new site, we should make sure we do not end up removing important content. Most of the things that have not been moved over seem to be either Wikidata specific or not wortwhile including in their current form.

The only clear thing we might want to also link from the new site is the data model primer.

Another concern I have with redirecting is that currently we might be pointing to this page for the Wikidata specific content on it. Those links will need to be updated.

**Comment by lydiapintscher** [comment]
Let's please discuss the best way to do this when I am back next week.

**Comment by JeroenDeDauw** [comment]
Still need to do this. @lydiapintscher @tobijat
