### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/Wikiba.se-2017#28]
Serving the content over HTTPS would be great. We might not have user sessions that can be hijacked, but it's good form to protect against injection attacks.

**Comment by AbrahamWMDE** [comment]
then we need to buy a ssl-certificate for the domain.

**Comment by Ladsgroup** [comment]
We are moving this github repo to gerrit and its issues to phabricator. This one is already being tracked down in https://phabricator.wikimedia.org/T155359
