### ISSUE TITLE
Development page has Wikidata specific stuff

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/Wikiba.se-2017#3]
`/development` links to thing such as the Wikidata status updates. The site is about the Wikibase software, not the Wikidata project. (So this is like placing Wikipedia news on MediaWiki.org)

**Comment by JeroenDeDauw** [comment]
@jakob-WMDE this page for instance links to the build status of the Wikibase.git repository. This website is not just about the things in this git repository. It's about all the things you can find on the components page, some of which are not used at all by Wikibase.git. (And Wikibase.git will hopefully soon turn into WikibaseRepo.git and WikibaseClient.git)

**Comment by JeroenDeDauw** [comment]
@AbrahamWMDE

**Comment by lydiapintscher** [comment]
While you are right we will link to this stuff for now. There are no resources to maintain for example the user documentation twice.

**Comment by AbrahamWMDE** [comment]
What Jeroen says. 

@lydiapintscher no one wants to maintain docu at two place and we will not do that in the future.

**Comment by lydiapintscher** [comment]
So what do you suggest for development updates?

**Comment by JeroenDeDauw** [comment]
We do not currently have development updates _for the Wikibase software_, so this is not something we need to take care of now.

Well, not completely, we do have releases and associated release notes for each component.

Most projects seem to have a blog that sees post for the most significant events or points of interest, which tends to not be the same as each release for each component.
