### ISSUE TITLE
How to install Wikibase on Debian

### ISSUE THREAD

**Issue by pachevalier** [wmde/Wikiba.se-2017#30]
Hello, 

I'd like to install Wikiba.se on my local machine (Debian 8). I've installed Sculpin but I was unable to run the `composer install` command. Do you have any clue ?

**Comment by JeroenDeDauw** [comment]
This repo contains the resources of the wikiba.se website. It is not the Wikibase software itself.

**Comment by pachevalier** [comment]
Ok. Thanks for your answer
