### ISSUE TITLE
Host wikibase rdf ontology file on wikiba.se

### ISSUE THREAD

**Issue by brightbyte** [wmde/Wikiba.se-2017#32]
The file docs/ontology.owl from the Wikibase repo should be available under the wikiba.se domain, using a path like http://wikiba.se/schema/ontology-0.0.1.owl  with the appropriate versioning.

There should be redirects (303) from http://wikiba.se/ontology and http://wikiba.se/ontology-beta to the latest version of that file.

Relevant phabricator tickets:
- https://phabricator.wikimedia.org/T97195 
- https://phabricator.wikimedia.org/T93207
- https://phabricator.wikimedia.org/T94747

**Comment by JeroenDeDauw** [comment]
Is this on the same level as the data model, or is it specific to a subset of potential usecases?

From the file:

> The system ontology of Wikibase, which is used to describe the user-created content.

That seems specific to Wikibase Repository to some extend. Though even there not all the things are necessarily user created.

I'm wondering what the motivation for putting this in the top level NS is.

**Comment by Benestar** [comment]
I've uploaded a patch to remove that specific sentence: https://gerrit.wikimedia.org/r/#/c/214915/

**Comment by JeroenDeDauw** [comment]
We have http://wikiba.se/ontology-1.0.owl, so can this be closed?

**Comment by mariushoch** [comment]
The file is not up to date, though… who can update it?

**Comment by lydiapintscher** [comment]
@JeroenDeDauw can

**Comment by JeroenDeDauw** [comment]
The site contains the latest git... I guess @mariushoch means the file needs to be updated by someone in the git repo...

For which you probably want to create a new ticket and not reuse a related one

**Comment by thiemowmde** [comment]
#55 refreshes the copy, but does not really solve the problem of this going out of date. What can we do?

**Comment by mariushoch** [comment]
@JeroenDeDauw This repo has been updated (#55), now someone(?) needs to update the actual site.

**Comment by Ladsgroup** [comment]
This should be part of https://phabricator.wikimedia.org/T166299. I'm closing this.
