### ISSUE TITLE
Homepage is about Wikibase Repo

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/Wikiba.se-2017#4]
The homepage is about the Wikibase Repo application, especially the "features" section. It's a very nice overview for Wikibase Repo, and we definitely want it on the site. However Wikibase Repo is not the only application. At the moment we also have Wikibase Client. Soon we will also have Wikibase Query. And there are many others that we can create.

```
Wikibase allows the collaborative editing of structured data on top of MediaWiki
```

That is specific to the MediaWiki extensions, Wikibase Repo and Wikibase Client. The core concepts of the Wikibase platform are MediaWiki agnostic, and can be used together with very different delivery and data access mechanisms. So while this line is fine if `Wikibase` is changed to `Wikibase Repo`, we need something more general on the homepage. Perhaps something along the lines of

```
Wikibase is a platform for creating, managing and sharing structure data
```

**Comment by JeroenDeDauw** [comment]
@AbrahamWMDE

**Comment by lydiapintscher** [comment]
We will mention MediaWiki on that page.

**Comment by AbrahamWMDE** [comment]
I want to go for this 

"Wikibase is a platform for creating, managing and sharing structure data, e.g. on top of MediaWiki"

or 

"Wikibase is a platform for creating, managing and sharing structure data, e.g. on top of MediaWiki as it is done for the Wikidata project"

**Comment by ghost** [comment]
@JeroenDeDauw @lydiapintscher
I just talked to @AbrahamWMDE about this and we decided to
- change the sentence on the front page as suggested
- remove the "Development" page and replace it with a "Projects" page that Wikidata will be a prominent part of and from which we can link to the mediawiki.org extension page
- move the documentation to the "Contribution" page
- move content about the current development to the "About" page

**Comment by JeroenDeDauw** [comment]
The [Doctrine project](http://www.doctrine-project.org/index.html) has some similarity to Wikibase. It's not a single thing, but a collection of "projects". The main page does not talk about the Doctrine ORM, even though that might be the "big thing most people think about when they hear about the project", much like Wikibase Repo in our case. It then has separate documentation for each project, avoiding the context problems the wikiba.se site currently has (both the old and new versions).

This makes me think that putting the installation instructions for Wikibase Repo and Wikibase Client in the new site was a mistake. We will always have these docs on the [extension page](https://www.mediawiki.org/wiki/Extension:Wikibase_Repository)s on MediaWiki org, where people expect them to be. So it seems to make more sense to just refer to those from a dedicated page about the particular extension.

**Comment by AbrahamWMDE** [comment]
@JeroenDeDauw sounds good and reasonable
