### ISSUE TITLE
Load all resources from our domain

### ISSUE THREAD

**Issue by Benestar** [wmde/Wikiba.se-2017#46]
Currently, the font-awesome css gets loaded from another domain. That seems to be a privacy issue.

See https://github.com/wmde/Wikiba.se/blob/master/source/_views/default.html#L8

**Comment by JeroenDeDauw** [comment]
Do you mean that `bootstrapcdn` can see who visits wikiba.se?

**Comment by thiemowmde** [comment]
Again, you amaze me with a rhetorical question that does not add anything but confusion. Bene even linked to the line in question. It loads a resource from bootstrapcdn.com. When looking at their site, it does not say anything about privacy. There is not even an imprint. It runs Google Analytics and multiple ad networks. It's pretty obvious we sell a tiny little bit of our visitors privacy to these sites. Do we have to?

**Comment by JeroenDeDauw** [comment]
@thiemowmde this question was not rhetorical. What is obvious to you might not be to someone else. I'd very much appreciate less aggressive answers/replies from you.

**Comment by thiemowmde** [comment]
Bene pointed to a line of code. You looked at it. You see it pulls a resource from bootstrapcdn.com. So yes, bootstrapcdn.com can see our visitors. So I can not help but ask what the intent of your question is, when you obviously understood what Bene meant?

**Comment by JeroenDeDauw** [comment]
As his intent was not explicitly specified, I made a guess based on the code, and posted a question to verify this guess is correct. You appear to be assuming bad intend on my part and responding in a judgemental way based on that incorrect assumption. If you had replied "Indeed", then I would have gone "oh ok, +1".

**Comment by Ladsgroup** [comment]
Moved to phabricator: https://phabricator.wikimedia.org/T171656
