### ISSUE TITLE
sculpin.json missing?

### ISSUE THREAD

**Issue by thiemowmde** [wmde/Wikiba.se-2017#5]
When I follow the instructions in the README it stops working at step `sculpin install` with `[InvalidArgumentException] Composer could not find the config file: /var/www/Wikiba.se/sculpin.json`.

**Comment by JeroenDeDauw** [comment]
I also ran into this. I just copied the `composer.json` file and ran the command again. The command hang and I aborted it, though it did install everything needed for the stuff to work. Indeed need to fix this.

**Comment by JeroenDeDauw** [comment]
@jakob-WMDE

**Comment by JeroenDeDauw** [comment]
I updated the README. Just using composer for the installation appears to work. Will file a bug upstream.

**Comment by JeroenDeDauw** [comment]
Filed here https://github.com/sculpin/sculpin/issues/150
