### ISSUE TITLE
Index to ontology

### ISSUE THREAD

**Issue by rain1024** [wmde/Wikiba.se-2017#59]
Hi all,

I installed wikibase successfully to my wiki. I created some entities and properties. But I don't know how to index these data to Jena server. So I can create SPARQL endpoint like wikidata https://query.wikidata.org/

Is this possible? Thank you so much.

**Comment by thiemowmde** [comment]
This is not a support forum for the Wikibase software, but the bug tracker for the [wikiba.se](http://wikiba.se) website.

There are multiple exporters for JSON and RDF exports, to be run via [repo/maintenance/dumpRdf.php](https://github.com/wikimedia/mediawiki-extensions-Wikibase/blob/master/repo/maintenance/dumpRdf.php).

**Comment by rain1024** [comment]
sorry for post in wrong place. Thank you so much for pointing me to repo/maintenance/dumpRdf.php.

**Comment by JonasKress** [comment]
If you would like to have the same setup as on query.wikidata.org here is the documentation for that
https://www.mediawiki.org/wiki/Wikidata_query_service/User_Manual#Standalone_service

**Comment by rain1024** [comment]
@JonasKress Thank you so much for this usefull link. I installed wikidata-query-rdf and wikidata-query-gui successfully. My team can have our own query service (like query.wikidata.org) for our Wikibase.

![](http://i.imgur.com/7QutlGa.png)

Now I come with the question, How can I import data dynamically (e.g. from python, maintenance scripts) to our Wikibase? We considered two ways, first one is with Wikibase API, but it kinds of slow (we have ~100k new entities to dump to Wikibas), second one is WikibaseImport (https://github.com/filbertkm/WikibaseImport), however it just import from wikidata (not support from our own RDF). Is there a clever way to do this task? 

PS: Can I have your contact for more questions about Wikibase? Comments in this issue maybe is not appropriate. Thank you so much.

**Comment by thiemowmde** [comment]
Again, this is not a support channel. Please find an appropriate channel in the contact section at https://www.wikidata.org. I suggest the mailing list.

**Comment by lydiapintscher** [comment]
@rain1024 you can email me at lydia.pintscher@wikimedia.de but the public mailing list is usually better. I'd love to hear more by email about what you're doing with Wikibase.
