### ISSUE TITLE
bootstrap not found

### ISSUE THREAD

**Issue by thiemowmde** [wmde/Wikiba.se-2017#6]
With the updated README I got `Development server is running at http://localhost:8000`. Fine. But:

`"GET /components/bootstrap/css/bootstrap.min.css HTTP/1.1" 404`

I guess I have to rune some of the commands in the README in a specific folder. Not sure if something is wrong or just missing in the README.

PS: Moving the existing `components` folder one down does not help, there is no bootstrap.min.css.

**Comment by JeroenDeDauw** [comment]
Cannot reproduce

```
git clone git@github.com:wmde/Wikiba.se.git site
cd site/
composer install
sculpin generate --watch --server
```

works fine for me...

**Comment by thiemowmde** [comment]
I tried this several times now. There is no `bootstrap.min.css` in the folder given in the template. #7 fixes that for me.

**Comment by thiemowmde** [comment]
Next attempt: #11.
